const countries = [
  { code: "EG", name: "مصر", value: "مصر", name_en: "Egypt" },
  { code: "SA", name: "السعودية", value: "السعودية", name_en: "Saudi Arabia" },
  {
    code: "AE",
    name: "الإمارات",
    value: "الإمارات",
    name_en: "United Arab Emirates",
  },
  { code: "KW", name: "الكويت", value: "الكويت", name_en: "Kuwait" },
  { code: "QA", name: "قطر", value: "قطر", name_en: "Qatar" },
  { code: "OM", name: "عُمان", value: "عُمان", name_en: "Oman" },
  { code: "BH", name: "البحرين", value: "البحرين", name_en: "Bahrain" },
  { code: "JO", name: "الأردن", value: "الأردن", name_en: "Jordan" },
  { code: "IQ", name: "العراق", value: "العراق", name_en: "Iraq" },
  { code: "SY", name: "سوريا", value: "سوريا", name_en: "Syria" },
  { code: "LB", name: "لبنان", value: "لبنان", name_en: "Lebanon" },
  { code: "MA", name: "المغرب", value: "المغرب", name_en: "Morocco" },
  { code: "TN", name: "تونس", value: "تونس", name_en: "Tunisia" },
  { code: "DZ", name: "الجزائر", value: "الجزائر", name_en: "Algeria" },
  { code: "YE", name: "اليمن", value: "اليمن", name_en: "Yemen" },
  { code: "SD", name: "السودان", value: "السودان", name_en: "Sudan" },
  { code: "LY", name: "ليبيا", value: "ليبيا", name_en: "Libya" },
  { code: "PS", name: "فلسطين", value: "فلسطين", name_en: "Palestine" },
  { code: "TR", name: "تركيا", value: "تركيا", name_en: "Turkey" },
  {
    code: "US",
    name: "الولايات المتحدة",
    value: "الولايات المتحدة",
    name_en: "United States",
  },
  {
    code: "GB",
    name: "المملكة المتحدة",
    value: "المملكة المتحدة",
    name_en: "United Kingdom",
  },
  { code: "FR", name: "فرنسا", value: "فرنسا", name_en: "France" },
  { code: "DE", name: "ألمانيا", value: "ألمانيا", name_en: "Germany" },
  { code: "IT", name: "إيطاليا", value: "إيطاليا", name_en: "Italy" },
  { code: "ES", name: "إسبانيا", value: "إسبانيا", name_en: "Spain" },
  { code: "CA", name: "كندا", value: "كندا", name_en: "Canada" },
  { code: "AU", name: "أستراليا", value: "أستراليا", name_en: "Australia" },
  { code: "RU", name: "روسيا", value: "روسيا", name_en: "Russia" },
  { code: "CN", name: "الصين", value: "الصين", name_en: "China" },
  { code: "JP", name: "اليابان", value: "اليابان", name_en: "Japan" },
  { code: "IN", name: "الهند", value: "الهند", name_en: "India" },
  { code: "BR", name: "البرازيل", value: "البرازيل", name_en: "Brazil" },
  {
    code: "ZA",
    name: "جنوب أفريقيا",
    value: "جنوب أفريقيا",
    name_en: "South Africa",
  },
  {
    code: "KR",
    name: "كوريا الجنوبية",
    value: "كوريا الجنوبية",
    name_en: "South Korea",
  },
  { code: "AR", name: "الأرجنتين", value: "الأرجنتين", name_en: "Argentina" },
  { code: "MX", name: "المكسيك", value: "المكسيك", name_en: "Mexico" },
  { code: "SE", name: "السويد", value: "السويد", name_en: "Sweden" },
  { code: "NL", name: "هولندا", value: "هولندا", name_en: "Netherlands" },
  { code: "CH", name: "سويسرا", value: "سويسرا", name_en: "Switzerland" },
];

export default countries;
